### ISSUE TITLE
Переработка редактора

### ISSUE THREAD

**Issue by GTDarkNightmare** [torrentpier/torrentpier#11]
Обернуть редактор в функцию function call_editor($size,$btn_cfg = array()). Позволит вызывать редактор с требуемыми кнопками (требуемым функционалом) в любом месте и подгружать его с помощью ajax. Так же позволит избавится от дублирующегося кода, упростить написание модификаций, требующих редактора.

Предполагаемые аргументы:
$size - размер редактора
$btn_cfg - массив конфигураций редактора: необходимые для вызова кнопки. Возможные ключи конфигурации: all - вызвать все кнопки, массив необходимых кнопок и exclude с указанием кнопок, которые не требуется выводить (выводить все кроме).

**Comment by Exile37** [comment]
Текущий редактор будет заменен. Соответственно механизм расширения тоже такого рода не нужен.
