### ISSUE TITLE
Поддержка utf8mb4 (emoji)

### ISSUE THREAD

**Issue by Exileum** [torrentpier/torrentpier#124]
Для поддержки эмодзи требуется конвертация базы данных в новую кодировку utf8mb4, что соответственно несколько поднимает требования к используемой версии MySQL (>5.1), но в современных реалиях отсутствие этой поддержки просто преступление. Более того, целый ряд багов вылазит именно из-за отсутствия этой поддержки, например с заголовками тем.

**Comment by Exile37** [comment]
Опционально готовое решение описано [вот здесь](https://xenforo.com/community/threads/true-utf-8-support-mysql-utf8mb4.90122/).

**Comment by VasyOk** [comment]
Для 2.1.6. смены не будет. используем это https://github.com/Ranks/emojione

**Comment by yukoff** [comment]
It would be nice to have a possibility to set collation as well - the default utf8_general_ci doesn't work nicely for eg. ukrainian or polish langs.

**Comment by yukoff** [comment]
We're doing a database conversion to `utf8mb4`/`utf8mb4_unicode_ci` in hurtom/toloka#74 - we're however have columns in `utf8_bin`, so instead `CONVERT TO` we've to use two alters with `MODIFY` to BLOB and then back to proper type - this allows to avoid conversion.

**Comment by Exile37** [comment]
@yukoff, that issue also goes into a migration plan for Laravel. Database collation will depend on it.
