### ISSUE TITLE
[Insight] Files should not be executable

### ISSUE THREAD

**Issue by VasyOk** [torrentpier/torrentpier#144]
> Your project contains files with permissive permissions. In order to avoid opening a security breach, you should restrict execution rights on following files: 
- crossdomain.xml

```bash
chmod a-x 'crossdomain.xml'
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/1a5d5098-e0b0-45c2-816a-020dfd50acaf/analyses/167?status=violations)_

**Comment by Exile37** [comment]
Resolved #145
