### ISSUE TITLE
Avif images support for forum (best quality/size image format), better than webp

### ISSUE THREAD

**Issue by koloved** [torrentpier/torrentpier#1659]
Sample:
[url=https://postimg.cc/1njDMQVg][img]https://i.postimg.cc/1njDMQVg/38b9b5ee-b916-4948-9049-5fada11f8f11.avif[/img][/url]

**Comment by belomaxorka** [comment]
Will be implemented! Thanks for issue

**Comment by belomaxorka** [comment]
Completed! (https://github.com/torrentpier/torrentpier/pull/1660)
