### ISSUE TITLE
Повышение безопасности

### ISSUE THREAD

**Issue by dimka3210** [torrentpier/torrentpier#20]
Нужно создать метод get_param, и использовать его для обращения к данным, принятым от клиента. Минимальная базовая защита должна заключаться хотя бы в замене спецсимволов на html-комбинации. 
Примерно выглядеть это должно так

```
/**
* @param $key string - ключ массива
* @param $source array - необязательный атрибут, по умолчанию берём из $_GET. 
* @param $default_value mixed - что возвращаем если не находим элемент в массиве. 
* @param $actions array - массив действий, по умолчанию array('htmlspecialcharst')
* @return mixed
*/
get_param(<key>, [source], [default value], [actions]);
```
*Пример использования 1*
```$page = get_param('page', $_GET, 1, array('intval'));```
Берём ключ page из $_GET. Он будет безопасен (т.к. пройдёт через intval()), а если его нет, то вернётся значение по умолчанию.

*Пример использования 2*
```$title = get_param('title', $_POST, '', array('strip_tags', 'htmlspecialcharst'));```

*Пример использования 3*
```$search_text = get_param('q');```

**Comment by Exile37** [comment]
https://github.com/torrentpier/torrentpier/issues/57 - запланирована иная реализация.
