### ISSUE TITLE
Avatar: doubled path  

### ISSUE THREAD

**Issue by ktrace** [torrentpier/torrentpier#227]
nginx log:
`34953 open() "/home/www/torrentpier/home/www/torrentpier/data/avatars/0/2/2.png" failed (2: No such file or directory), client: 192.168.0.77, server: 192.168.0.13, request: "GET /home/www/torrentpier/data/avatars/0/2/2.png HTTP/1.1"
`
TP v2.1.6, direct http://192.168.0.13/data/avatars/0/2/2.png - OK.

**Comment by Exile37** [comment]
Fixed in #302.
