### ISSUE TITLE
Refactor anouncer

### ISSUE THREAD

**Issue by Exileum** [torrentpier/torrentpier#248]
Рассмотреть возможность использования http://reactphp.org/ или т.п. методик для анонсера.

**Comment by yukoff** [comment]
В [symfony/http-kernel](http://api.symfony.com/3.3/Symfony/Component/HttpKernel/HttpKernel.html) есть работа с событиями, раз речь идет об использовании их же HttpFoundation то есть смысл использовать его. Тут вкупе с сессиями вырисовывается некий рефакторинг, чтоб сессии выбирались из кеша, а все, что надо писать в базу делать по событию `TERMINATE` после того, как ответ отправлен.

**Comment by Exileum** [comment]
It will be implemented in the long term.
