### ISSUE TITLE
Новый шаблонизатор: Twig

### ISSUE THREAD

**Issue by Exile37** [torrentpier/torrentpier#3]
Переделать текущий шаблон на Bootstrap, попутно внеся изменения в шаблонизатор, обновив его на более современное решение.

**Comment by KaRpIkS** [comment]
И какой шаблонизатор планируете использовать?

**Comment by Exile37** [comment]
Сто-то из общепринятого. Были мысли про Smarty, посмотрим.

**Comment by VasyOk** [comment]
Не люблю шаблонизаторы, но я бы рассматривал [twig](http://twig.sensiolabs.org/). Причина проста - для продакшена можно [скомпилировать](http://twig.sensiolabs.org/doc/installation.html#installing-the-c-extension) php расширение, что позволит увеличить скорость генерации на боевом сервере, а для разработки достаточно php исходников

**Comment by Exile37** [comment]
Шаблонизатор определен - Twig. Текущий шаблон на него будет перенесен возможно сразу с заменой на Bootstrap.

**Comment by KaRpIkS** [comment]
Будет стандартный код использоваться или будет надстройка? Как реализовано в phpbb?

**Comment by Exile37** [comment]
Стандартный, без надстроек. Синтаксис шаблонов соответственно изменится.
