### ISSUE TITLE
BB-code из админки

### ISSUE THREAD

**Issue by dlarchikov** [torrentpier/torrentpier#36]
Думаю стоит перенести регулярки из файла в БД. Это позволит пользователям (администраторам трекеров) добавлять новые коды на лету, на основе уже существующих.
# Плюсы
- Не нужно погружаться в код.
- Быстрая мастабируемость
- Настройка доспупа к тем, или иным кодам
# Минусы
- Добавлояется незначительная нагрузка на базу/кеш при добавлении сообщения

**Comment by Exile37** [comment]
Первичная реализация была в ветке https://github.com/torrentpier/torrentpier/commit/048d7ddc48754b7b06bdfd6e5f755381460a0160 - но с учетом смены шаблонизатора и сопутствующих изменениях не столь актуально. Хотя, почти наверняка, потребуется в дальнейшем.

**Comment by Exile37** [comment]
С учетом что снесли ветку - прикладываю патч, вдруг пригодится.
[patch_issue36.diff.zip](https://github.com/torrentpier/torrentpier/files/714970/patch_issue36.diff.zip)

**Comment by Exileum** [comment]
Won't fix.
