### ISSUE TITLE
Database migraions (doctrine or phinx)

### ISSUE THREAD

**Issue by yukoff** [torrentpier/torrentpier#427]
Is there any plans on using database migrations (doctrine by means of `artisan` or phinx)? We're currently working on this for our project based on TP and there are either way possible. The other thing is that both will convert columns (eg. smallints etc) to their php equivalents - initial schema diff will be quite big and further generated migration will be altering almost each and every table/column.

One more thing is that some table don't have PK - at least doctrine won't work without that.

**Comment by Exile37** [comment]
@yukoff in the future on experimental branch we want to move on full Laravel-stack, thus database migrations and seeding will be based on it.

**Comment by yukoff** [comment]
@Exile37 Good to know! BTW there are 4 tables without PK constraints:
* bb_attach_quota
* bb_bt_dlstatus_snap
* bb_log
* bb_topics_watch

As laravel migrations based on doctrine (which in turn won't work with tables w/o PK) this should be addressed beforehand (I mentioned this in issue description). Should I create another issue? Or I can create a PR to address this, so we'll be able to review/discuss suggested change.

**Comment by Exileum** [comment]
Will be implemented in version 2.3.1.
