### ISSUE TITLE
Неделя без форума. А может и целая вечность

### ISSUE THREAD

**Issue by Exile37** [torrentpier/torrentpier#428]
<p align="center"><a href="https://torrentpier.me/"><img src="https://torrentpier.me/forum/styles/default/xenforo/bull-logo.svg" width="400px" /></a></p>

Доброго времени суток.

Наверное, это несколько необычное обращение, но в общем и целом дальше так продолжаться не может. Проекту TorrentPier уже больше 10 лет, на протяжении которых он развивался только силами нескольких разработчиков. Большую часть времени их было не больше трех. Состав регулярно менялся, но в общем и целом - разработка зависела от небольшого числа людей. Остальные трудами только пользовались.

Проходят года, а ситуация не изменилась ни на йоту. Только разработчиков стало двое, а того и гляди и еще меньше. Никакой отдачи от сообщества. Никакого желания у сообщества помогать с развитием проекта. Даже после трех релизов за короткий срок особой обратной реакции не поступило. Отсюда можно сделать только два вывода: проект никому не нужен или просто люди хотят только пользоваться, не предоставляя никакой обратной связи взамен. Поэтому на этой неделе по большей части решится судьба форума. Форум требует вложений как денежных, так и временных, а последних особенно не хватает - лично мне хочется для души заниматься кодом проекта, а не следить за работой форума. Но это могло бы иметь смысл, если бы от пользователей форума поступала обратная связь. Сейчас в достаточно активной разработке находится версия 3.0, но с таким же уровнем обратной связи - в ней нет никакого смысла.

Я хочу видеть сообщество единомышленников, которые готовые передавать часть своих наработок в виде кода и идей обратно проекту. Я хочу видеть людей, заинтересованных в развитии проекта, в том числе прикладывая личные усилия. Я хочу видеть единомышленников, а не нахлебников. Это совершенно нормально для любого живого opensource-проекта. Если у нас это не получится - значит наш проект мертв, форум закрыт, а все новые версии будут делаться без оглядки на обратную совместимость как таковую в принципе исключительно для своего саморазвития.

Чем можно изменить ситуацию?

1. Сделать форк проекта и [подготовить pul-request](https://github.com/torrentpier/torrentpier/pulls) со своими доработками.
1. Описать какую-то возможность или функциональность, которую хотелось бы видеть в проекте используя [раздел с issues](https://github.com/torrentpier/torrentpier/issues). Примеров там достаточно.
1. Присоединиться к обсуждению любой существующей инициативы, хотя бы этой.
1. Задуматься о том, что проект жив только если люди готовы давать ему что-то взамен.

Если ничего не изменится - форум открыт не будет и все модификации, которые там есть будут выложены тут в виде суб-репозиториев организации. Если сообщество подтвердит что готово развиваться - форум будет жить. Хотя его ценность в современном мире разработки стремится к нулю.

А для всех остальных, есть наш уютный чат в Slack, где можно обсудить как вопросы по движку, так и это обращение в целом: <a href="http://torrentpier.herokuapp.com/"><img src="http://torrentpier.herokuapp.com/badge.svg" alt="Slack"></a>

**Comment by loginexe** [comment]
На хую видал твой проект, пользуюсь пхбб и его развиваю, а ты членосос со своими понятиями иди на хуй

**Comment by Exile37** [comment]
@loginexe что-то вклада в профиле никуда не видно только 🌝

**Comment by loginexe** [comment]
я же не  идиот чтобы писать с основы, но что то ты долбаеб ты доказывал это неоднократно,  если бы ты был адекватном, то можно было бы подумать о финансировании, но поскольку ты хуило, то пусть этот проект умрет

**Comment by loginexe** [comment]
Хотя мое мнение это пафос и ты пытаешься отмутить деньги

**Comment by loginexe** [comment]
пхбб будет жить)

**Comment by Exile37** [comment]
@loginexe о каких деньгах вообще речь? Их нет от проекта в принципе, да и не нужны. Инициативных людей нет.

**Comment by bard0962** [comment]
Согласен с Artzhuna адекватность нужна, тогда наверно и народ будет по активнее.
Что косаемо движка он достаточно хорош и по настройкам гибкий меня устраивает полностью.

**Comment by ImDim** [comment]
Как по мне, форумы уже давно морально устарели. Движок был не плохой, но вероятно нужно пересмотреть стратегию и выпустить абсолютно новый проект. Нет смысла уже в обратной совместимости, нужен новый глоток. 
Сейчас сам пишу двиг, для своих целей, взял функционал от DLE, модульность от WP и PageKit.

**Comment by Artzhuna** [comment]
Exile37, а почему вам деньги за проделанную работу ненужны? Как по мне, то работать на голом энтузиазме, без бабла, трудно. Вы не задумывались сделать несколько платных версий с их постоянной поддержкой? Например, так.

1. Free версия - это то что и сейчас, просто двиг с коробки.
2. Standart версия (цена $ ваша, адекватная) - добавить к движку несколько модулей от разработчика. Самых необходимых.
3. Pro версия (цена $ ваша, адекватная) - добавить к движку больше модулей.

Для изучения вопроса, какие модули нужны в версиях проведите голосование среди пользователей.

Смысл постоянно поддерживать модули в актуальном/рабочем состоянии для всех купивших. Каждая минорная версия гарантирует работоспособность пакета модулей. Сделать ПОДРОБНЫЙ FAQ по установке и настройкам. С выходом новой версии движка, новый пакет услуг по всем тарифам продлевать или покупать заново. Лично для меня было проще заплатить за версию с нужными мне модулями и не париться по поводу их работоспособности. Думаю я не одинок.

Тут и пользователей бы активных прибавилось, да и энтузиазм у разработчиков был бы здоровый.

**Comment by ImDim** [comment]
Artzhuna, еще можно сделать встроенный маркет с платными и бесплатными модулями, шаблонами. Как вариант дать возможность продавать свои модули/шаблоны сторонним разработчикам в маркете и при этом брать комиссию с продаж. Так у livestreet вроде организовано, за счет этого движок и развивается.

**Comment by U1610113** [comment]
WTF

**Comment by Logoud** [comment]
**Exile37** очень жаль если форума не станет, проект ваш нужный интересный, использую ваш модифицированный движок года 3, я не кодер конечно и помочь в разработке не смогу, но я всеми руками за проект, и готов помочь чем могу. За форумом следить можно набрать модераторов, адекватных конечно, а вы как разработчик будите заниматься чисто кодом.
