### ISSUE TITLE
Пропадает jumpbox со страницы 

### ISSUE THREAD

**Issue by PR0TEKT0R** [torrentpier/torrentpier#435]
После правки строки 
$bb_cfg['cookie_secure'] = $domain_ssl ? true : (!empty($_SERVER['HTTPS']) ? true : false);
исчезает  jumpbox , браузер ругается на строчку 
var cookieSecure = {$bb_cfg['cookie_secure']}; в page_header.tpl

**Comment by PR0TEKT0R** [comment]
Сегодня было замечено, что так же отваливается ajax, сполеры, и возможность редактировать релиз.

**Comment by VasyOk** [comment]
@PR0TEKT0R если это относится к разным местам, создай issue новые и опиши как воспроизвести.

**Comment by PR0TEKT0R** [comment]
А смысл заново писать, все это происходит после применения данного коммита.
https://github.com/Exile37/torrentpier/blob/b54c9d0c2eedba13aee51837ccaf03be3a1e8820/library/config.php#L370

**Comment by Exile37** [comment]
Fixed in #436.
