### ISSUE TITLE
Undefined index: ATOM_GLOBAL_FEED

### ISSUE THREAD

**Issue by PR0TEKT0R** [torrentpier/torrentpier#437]
Нотис в логах PHP Notice:  Undefined index: ATOM_GLOBAL_FEED 
https://github.com/torrentpier/torrentpier/blob/2.2/library/includes/functions_atom.php#L39

![bag1](https://user-images.githubusercontent.com/29069651/28898231-66a6a464-77ed-11e7-9f8a-f8c28af62ba2.png)
![bag2](https://user-images.githubusercontent.com/29069651/28898240-717ec3d0-77ed-11e7-9de7-295641b342bd.png)
так же отсутствует название атом ленты 0.atom
![title_feed](https://user-images.githubusercontent.com/29069651/28898269-97b386c6-77ed-11e7-9326-0ad6e6b1d6bd.png)

**Comment by ua2004** [comment]
Why is this issue closed? I have the same problem.

**Comment by Exile37** [comment]
It was fixed in 2.2.3.

**Comment by ua2004** [comment]
I confirm that it wasn't. I have this issue on the fresh 2.2.3. Appears on regular basis. I assume it has something to do with cron job `update_forums_atom.php`.

**Comment by PR0TEKT0R** [comment]
@ua2004 
open `functions_atom.php` 
find 
`$forum_data['forum_name'] = $lang['ATOM_GLOBAL_FEED'];`
replace
`$forum_data['forum_name'] = 'SITE NAME';`
a temporary solution to this problem

**Comment by ua2004** [comment]
Can you please briefly describe the cause of this issue?
