### ISSUE TITLE
Exception is thrown if there are users having birthdays on current week

### ISSUE THREAD

**Issue by yukoff** [torrentpier/torrentpier#447]
```
Whoops\Exception\ErrorException thrown with message "A non well formed numeric value encountered"

Stacktrace:
#1 Whoops\Exception\ErrorException in /var/www/html/index.php:387
#0 Whoops\Run:handleError in /var/www/html/index.php:387
```

The problem here is with [line 382](https://github.com/torrentpier/torrentpier/blob/master/index.php#L382) (there are some modifications on file so line number differ), with this part to be exact:
```php
birthday_age($week['user_birthday'] - 1)
```

I'm just not getting what it supposed to do... Subtract `1` from date string, say `1970-01-01`? Or subtract `1` from the user's age (which won't work either as in this case it would be subtraction from a string in format `%d  %s`)?
```php
birthday_age($week['user_birthday']) - 1
```

And is that subtraction required at all?

**Comment by Exile37** [comment]
Fixed.
