### ISSUE TITLE
PHP Notice:  A non well formed numeric value encountered

### ISSUE THREAD

**Issue by PR0TEKT0R** [torrentpier/torrentpier#450]
Нотис при отображении празднующих день рождения в ближайшие 7 дней. 
В краце: `PHP Notice:  A non well formed numeric value encountered in /home/admin/web/site.ru/public_html/index.php on line 383`
На демке нотиса нет так как в 
https://github.com/torrentpier/torrentpier/blob/2.2/index.php#L382
отсутствует (-1) 
И отображается возраст не тот что будет а по факту, сколько уже есть.
Если качать с центра загрузки 223 версию то там данные строчки отличаются а именно (-1) присутствует, и с высокой вероятностью будет лезть нотис как и у меня.

**Comment by Exile37** [comment]
EУже было исправлено ранее: https://github.com/torrentpier/torrentpier/commit/a6ab8ac4310fea4354dd6b11883c6abb9e97a11b
