### ISSUE TITLE
posting_tpl.tpl

### ISSUE THREAD

**Issue by Alexisback** [torrentpier/torrentpier#452]
in \styles\templates this file is found **posting_tpl.tpl**

how to enable and configure it?

**Comment by PR0TEKT0R** [comment]
![screenshot-2017-11-23 lossy torrentpier - bull-powered bittorrent tracker engine](https://user-images.githubusercontent.com/29069651/33173484-6438e5cc-d065-11e7-85de-1bd5966766c0.png)
![screenshot-2017-11-23 torrentpier - bull-powered bittorrent tracker engine](https://user-images.githubusercontent.com/29069651/33173499-6f440654-d065-11e7-989f-56a3b76019ce.png)

**Comment by Alexisback** [comment]
does not work 

a guide (in English, please)
![screen capture 210](https://user-images.githubusercontent.com/18039740/33173900-e7eef536-d066-11e7-8ecb-df2de0d09f4b.png)

**Comment by PR0TEKT0R** [comment]
you do not have a template, the error says exactly this. In order to include a template, you need to create it first.
There is not a big manual in Russian
https://torrentpier.com/forum/threads/video-faq-rabota-s-konstruktorom-shablonov.25844/

**Comment by Alexisback** [comment]
thanks PR0TEKT0R 

I watch videos to understand

another question

where does the template (both this and in Russian) translate, what is the file?

I am translating the forum from English to Italian (it has been translated badly and with errors)
with the main.php file

**Comment by PR0TEKT0R** [comment]
If you have installed torrent pier 223, at the moment when creating a new release template you will have problems, this time it does not work properly, developers know this problem, in the next version we are waiting for correction.
Please note
Skin Template Editor supports Russian only

**Comment by Alexisback** [comment]
Yes,
I have version 2.2.3

what do I need to install? 2.2.2 is it okay?

Skin Template Editor 
I can translate it (if i find the file with the strings in Russian)

**Comment by PR0TEKT0R** [comment]
it worked fine in 2.1.5
but this is quite an old version and most likely the bug will soon be fixed
All language packs are stored in the
https://github.com/torrentpier/torrentpier/tree/master/library/language
Russian language pack
https://github.com/torrentpier/torrentpier/blob/master/library/language/en/main.php

**Comment by Alexisback** [comment]
found the strings for Skin Template Editor
are inserted in posting_tpl.tpl
I can translate them
Thanks PR0TEKT0R  for you help

**Comment by Alexisback** [comment]
I managed to create a new model (not very difficult)
as he specified PR0TEKT0Rin version 2.2.3 does not work

I should install 2.1.5, but i have translated many lines into many files
main.php
posting_tpl
topic_tpl
functions
if i install 2.1.5 I can replace with 2.2.3 or are different files?

**Comment by Exileum** [comment]
Fixed in 2.3.0.
