### ISSUE TITLE
Переписанные группы - быстрее и проще

### ISSUE THREAD

**Issue by yumus** [torrentpier/torrentpier#49]
http://pastebin.com/tY1rqLRz
http://pastebin.com/tUkUPRum

**Comment by yumus** [comment]
Какая-то реакция на предложения будет?

**Comment by iGliX** [comment]
Все предложения просматриваются, в будущих версиях что-то из наработок возможно будет включено в вдижко, спасибо.

**Comment by PheRum** [comment]
This paste has been removed!

**Comment by yumus** [comment]
сек
