### ISSUE TITLE
info_hash improvements

### ISSUE THREAD

**Issue by MetalWarrior88** [torrentpier/torrentpier#501]
Нельзя пропускать бинарное значение info_hash через DB()->escape(). Также нужно добавить поддержку bittorent v2. К примеру qbittorent в качестве info_hash отправляет sha256 хэш порезаный до 20 бит для совместимости. Поэтому трекер выдает ошибку torrent not registered
Правки:
functions.php
```
	$info_hash     = pack('H*', sha1(bencode($info)));
	$info_hash2    = pack('H*', hash('sha256', bencode($info))); //varbinary 32bit
	//$info_hash_sql = rtrim(DB()->escape($info_hash), ' ');
	$info_hash_sql = bin2hex($info_hash);
	$info_hash2_sql= bin2hex($info_hash2);


	$sql = "SELECT topic_id
		FROM ". BB_BT_TORRENTS ."
		WHERE HEX(info_hash) = '$info_hash_sql' OR HEX(info_hash2) = '$info_hash2_sql'
		LIMIT 1";
```

```
$columns = ' info_hash, info_hash2,	post_id,  poster_id,  topic_id,  forum_id,  attach_id,    size,  reg_time,  tor_status';
$values = "x'$info_hash_sql', x'$info_hash2_sql', $post_id, $poster_id, $topic_id, $forum_id, $attach_id, '$size', $reg_time, $tor_status";
```
bt/announce.php
```
	//$info_hash_sql = rtrim(DB()->escape($info_hash), ' ');
	$info_hash_sql = bin2hex($info_hash);
	$passkey_sql   = DB()->escape($passkey);

	
	$sql = "
		SELECT tor.topic_id, tor.poster_id, tor.tor_type, u.*, u1.is_vip
		FROM ". BB_BT_TORRENTS ." tor
		LEFT JOIN ". BB_BT_USERS ." u ON u.auth_key = '$passkey_sql'
		LEFT JOIN bb_users u1 ON u1.user_id = u.user_id
		WHERE HEX(tor.info_hash) = '$info_hash_sql'  OR HEX(tor.info_hash2) LIKE '$info_hash_sql%'
		LIMIT 1
	";
```

**Comment by kovalensky** [comment]
Насчёт BitTorrent v2.

Также можно включить опцию показа v2 магнит ссылок.
Магнит ссылка формируется добавлением ещё одного ключа "&xt", с префиксом btmh, и sha256 сгенерированного info-хеша, что наверху и написали.
Т.е магнит ссылка будет выглядеть:
`magnet:?xt=urn:btih:ХЕШ_V1&xt=urn:btmh:ХЕШ_V2`

Чтобы узнать гибридный ли торрент файл:

`echo $torrent["meta version"]; // (int)=2`

После того, как мы выяснили, что торрент имеет признаки v2, нам нужно проверить, является ли он гибридным или только v2 совместимым.
v1 торренты имеют ключ "pieces", в то время как в гибридных есть два ключа "piece layers" (вне секции info) и "pieces" (внутри info).
Если ключи "meta version" и "piece layers" существуют без ключа "pieces", то этот торрент является только v2 совместимым.
```
if(isset( $torrent["piece layers"] )){
if(!isset( $torrent->info["pieces"] )){
// Отказ на загрузку. Только v2 совместимые торренты несовместимы со многими старыми версиями торрент клиентов, в отличии от гибридных.
}
}
```
Так же отлично было бы показывать хеш файлов, по ключу в info "pieces root" (он в бинарном виде, byte 32) в гибридных торрентах, что-то наподобие:
![312271d843d70e74f3d28a5d5712e0fb](https://user-images.githubusercontent.com/45331093/215251753-46e86797-f47d-4800-89da-f677fc193705.png)

**Comment by kovalensky** [comment]
Код для листинга всех файлов и папок с их хешами и размерами:
```
if(!isset($decoded["meta version"]) && !isset($decoded["piece layers"])){
   die(); // Это v1 торрент
  }

$torrent = $decoded_file["info"]["file tree"];
function printArrayNames($array, $parent = "") {
    foreach($array as $key => $value) {
        $current = $parent . "/" . $key;
        if(is_array($value) & strlen($key) !== 0) {
            printArrayNames($value, $current);
        } else {
            echo "<b>". substr($current, 1, -1) . "</b><br>Root hash: " . bin2hex($value["pieces root"]) . " Size: <i>" . $value["length"] . "</i><br><br>";
  }
    }
}
printArrayNames($torrent);
```

**Comment by kovalensky** [comment]
Если возникнет вопрос, как пользователи будут находить эти хеши файлов, то [программа](https://github.com/kovalensky/tmrr) для этого уже готова, остальное уже зависит от вас ребята :)
Если сделать отдельную страничку с информацией о файлах с их хешами, которую поисковики будут кешировать, то пользователи могут находить торренты, просто вбив в строку поиска хеш.
