### ISSUE TITLE
Вероятно код устарел

### ISSUE THREAD

**Issue by VasyOk** [torrentpier/torrentpier#51]
При просмотре форума и темы.

    Notice: Undefined index: tracker_status in library/includes/functions.php on line 2026
    Notice: Undefined index: tracker_status in viewforum.php on line 488
    Notice: Undefined index: tracker_status in library/includes/torrent_show_dl_list.php on line 17
    Notice: Undefined index: tracker_status in library/includes/torrent_show_dl_list.php on line 23
    Notice: Undefined index: topic_attachment in viewtopic.php on line 530
    Notice: Undefined index: post_attachment in viewtopic.php on line 746

**Comment by Exile37** [comment]
Не все еще смержено, да.
