### ISSUE TITLE
Внедрить менеджер зависимостей

### ISSUE THREAD

**Issue by VasyOk** [torrentpier/torrentpier#55]
Еще одна вещь, которая поможет и упростит работу это менеджер зависимостей. Так как внедрение начальное, что бы разобраться что да как предлагаю [Pimple](http://pimple.sensiolabs.org/). Простой менеджер и легко начать работать, так же это даст возможность избавиться от глобальных переменных.

Примеры:
из `DB()->query('select * from table');`
в `DI::instance()->get('db')->query('select * from table');`
или в `DI::instance()->db->query('select * from table');`

из `global $cfg;`
в `\TorrentPier\DI::instance()->get('config'); // Zend_Config`
или в `\TorrentPier\DI::instance()->config; // Zend_Config`

После обсуждения, взвешиваний за и против, готов помочь с внедрением.

**Comment by Exile37** [comment]
Да, интересно.

Про работу с базой - на самом деле была мысль перейти на соответствующий компонент ZF, вот даже ветка есть https://github.com/torrentpier/torrentpier/tree/Zend где в каком-то из коммитов последних это было реализовано вроде как (и даже анонсер  был спаян). Про качество кода не ручаюсь конечно, не смотрел. 

Про глобальные переменные - несомненно нужно. Вот только я может чего-то не понял, но например у нас в global в функции объявлены переменные $lang, $bb_cfg, $template, например - все три сразу. Как в предложенном варианте это объявление всего будет выглядеть в коде? В отношении использовании переменной $lang['home'] дальше в коде?

Какие есть аналоги у него? Бегло погуглил нашел про аналогичный в принципе компонент DI от Symfony 2. Я понимаю что возможно самый простой, но может есть более интересные варианты чтобы сразу делать на будущее, пускай и чуть сложнее?

PS. Вот относительно локализации и переменных вопрос тоже интересный. Нет каких-то наметок на то, что можно было бы использовать для локализации так же легко, как и сейчас, но более универсально так скажем?

**Comment by VasyOk** [comment]
По работе с бд.
Компонент ZF, на мой взгляд, действительно хорош, прост и легок в обращении. Из моего опыта перевода старой версии TP на Doctrine - очень тяжело перенести весь код TP, и там много подводных камней из-за которых можно "ногу сломать", поэтому с этим не стоит торопиться и внедрять постепенно, либо использовать обратную совместимость. Тут нужно хорошо подумать перед реализацией.

Про глобальные переменные.
Все и сразу очень тяжело и долго, изменять стоит постепенно. Но вот для примера:

    $lang = \TP\Container::instance()->lang;
    $lang['home'];

Но для twig, нужно подумать о реализации и сделать это иначе.

Про DI.
Аналогов [достаточно](https://github.com/ziadoz/awesome-php#dependency-injection). Однако DI от Symfony очень, я бы сказал, мощный и в данном контексте это будет тяжело как для понимания, так и в реализации. Схема описаний всех зависимостей получится очень большой, и нужно будет пересматривать архитектуру проекта. Я бы оставил его на 3-ю версию TP, когда будет сформирован взгляд на будущую версию и её архитектуру. А сейчас чем проще тем лучше и быстрее, плюс опыт и понимание механизма зависимостей.

Про переводы.
Полагаю, хорошо подойдет [Translation](https://github.com/symfony/translation) ([дока](https://symfony.com/doc/master/book/translation.html)). Его нужно применять с интеграцией Twig.

**Comment by Exile37** [comment]
За ссылку на Awesome PHP спасибо.

Базой данных можно заняться сейчас когда за пару дней постараюсь все же старый код добить по аттачам и перенести, чтобы уже можно было заняться не только ими. Про DI - в принципе ясно, вещь нужная, параллельно с работой с базой заодно можно будет начать хотя бы понемногу чистить. Переводы тогда вместе со сменой шаблонизатора на этап после этого.

PS. Что за проект перевода старой версии TP? Где-то можно ознакомиться?
PS. Ну и опять же вопрос, потому что насущный - компонент https://github.com/zendframework/zend-config для конфигурации использовать лучше или как вариант загнать все в тот же Pimple? Понимаю что наверное глупо и логично бы использовать первое, тем более что надо будет сокращать конфиг перенося почти все настраиваемое в админку.

**Comment by VasyOk** [comment]
> PS. Что за проект перевода старой версии TP? Где-то можно ознакомиться?

Прошу прощение, профессиональная привычка не разглашать заказчиков, пока (или в зависимости от контракта) работаю с ними.

> PS. Ну и опять же вопрос, потому что насущный...

Как раз занимаюсь. Чуть позже будет Issue и PR.

**Comment by VasyOk** [comment]
Добавил PR #56. Пример использования:

    $di = \TorrentPier\Di::getInstance();
    /** @var \Zend\Config\Config $config */
    $config = $di->config;
    /** @var \Zend\Db\Adapter\Adapter $db */
    $db = $di->db;

**Comment by Exile37** [comment]
Да, я там уже прокомментировал, еще раз спасибо. Надо будет еще по движку пробежаться, перенести в конфиг все переменные какие есть.

**Comment by VasyOk** [comment]
Обрати внимание.
- Defines из конфига вынес в отдельный файл.
- изменил конфиг, для \Zend\Config. Нужно подумать и что можно перенести в админку, а что оставить в конфиге.
- два провайдер сервиса, которые непременно нужно дорабатывать, поэтому бд не стоит торопиться переключать. Ищу возможность использовать Zend\Db\Adapter для работы со sphinx.
- сохранил совместимость со старым вариантом работы с бд, что бы оставить максимально рабочее состояние.

**Comment by Exile37** [comment]
Да, про перенос понятно, видел. Только немного не понял про какое именно переключение базы идет речь. Если про соседнюю ветку (с "адаптером" для ZF), то я откровенно говоря посмотрел и мне кажется, что там нужно сделать несколько иначе как минимум. А если речь про это, то немного не понял какая связь между конфигом и драйвером для базы (ну кроме захвата из базы информации). А про Sphinx - тут вообще давно в issues висит предложение перехода на SphinxQL, мне кажется самое время, там по уму и не должно будет проблем возникнуть - работа как с обычной базой.

**Comment by VasyOk** [comment]
> Только немного не понял про какое именно переключение базы идет речь.

Имею ввиду, механизм, который был для работы с бд - остался и работает, не смотрю на то что изменились настройки и добавилось подключение через zend-db.

> Если про соседнюю ветку

Я туда пока что не смотрел.

> А про Sphinx - тут вообще давно в issues висит предложение перехода на SphinxQL

Да идея хорошая, но там на самом деле не все так просто.

Будем пилить.

**Comment by VasyOk** [comment]
Нашел хорошую библиотеку которая поможет внедрить sphinxql. нужно обновить код, что бы сделать PR, с новым сервис провайдером или позже добавлю в #56.

**Comment by Exile37** [comment]
Не проблема, дозалить можно будет. Я просто если не особо против PR переписываю чтобы контролировать все изменения полностью, потому что есть пара моментов которые в целях обратной совместимости сохранять придется. Например изменение в #56 относительно доменного имени нужно будет проверить (прямое указание), т.к. на ряде конфигураций насколько помню возникала проблема с его неопределенностью, из-за этого серверные запросы и вводили. Ну просто как простейший пример. Так что в очередной раз огромная благодарность за помощь.

**Comment by VasyOk** [comment]
Добавлю еще один коммит, как закончу:
- интеграция #57 
- интеграция #3
