### ISSUE TITLE
Перейти на использование HttpFoundation компонент от Symfony

### ISSUE THREAD

**Issue by VasyOk** [torrentpier/torrentpier#57]
Компонент упрощает работу с получение данных (Request) от пользователя и отправкой ему ответа (Response). [Документация](http://symfony.com/doc/current/components/http_foundation/index.html).

пересекается с #20

**Comment by Exile37** [comment]
Он в себе и сессии содержит. Сессии тоже предложение на него перевести?

**Comment by VasyOk** [comment]
Да. сессии, куки и файлы

**Comment by Exileum** [comment]
Will be implemented in version 2.3.1.

**Comment by Exileum** [comment]
Fixed by #474.
