### ISSUE TITLE
Идеи по расширению возможности Zend\Config

### ISSUE THREAD

**Issue by VasyOk** [torrentpier/torrentpier#58]
1. Есть идея расширить конфига сделать "self", что то типа обращение к свои данным. Пример:

```php
return [
    'domain_name' => 'torrentpier.me',
    'db' => [
        'adapter' => 'Pdo_Mysql',
        'host' => 'self.domain_name',
    ],
    'sphinx' => [
        'adapter' => '{self.db.adapter}'
    ],
   'feedback_email' => 'admin@{self.domain_name}'
];
```

2. Обращаться по ключу разделенными точкой

```php
$config['db.host'] // 'torrentpier.me'
```

**Comment by Exile37** [comment]
Чем лучше/хуже текущего варианта? Сейчас же как понимаю та же самая надстройка над компонентом зенда только в виде своего провайдера. Или это в качестве отказа от глобальной переменной $bb_cfg?

**Comment by VasyOk** [comment]
> Чем лучше/хуже текущего варианта?
Конфиг уродлив, хочется сделать его более "смотрибельнее".

> Сейчас же как понимаю та же самая надстройка над компонентом зенда только в виде своего провайдера. Или это в качестве отказа от глобальной переменной $bb_cfg?

все верно. только это расширение текущих возможностей. Чуть позже сделаю PR будет нагляднее.

**Comment by Exile37** [comment]
Не спорю, конфиг страшный, еще и чистить нужно. С учетом постоянных PR - можно email чтобы в Slack пригласить, я комментарий после приглашения удалю вместе с ним? Было бы удобнее обсуждать некоторые вопросы чем тут.

**Comment by VasyOk** [comment]
diolektor at gmail.com

**Comment by Exile37** [comment]
Типа такого

**Comment by VasyOk** [comment]
done
