### ISSUE TITLE
Ошибка при добавлении категории

### ISSUE THREAD

**Issue by artems37rus** [torrentpier/torrentpier#627]
Возникает ошибка при попытке добавить новую категорию и в ней разместить форум, версия билда :
Bison (2.3.1)
Дата выпуска: | 18-03-2023
Ошибка возникает на главной странице форума при его просмотре

-----------
…\index.php:192
"Undefined offset: 12"
------------
Ошибка пропадает после чистки кэша, а именно \internal_data\cache\filecache
И вновь появляется при проделывании выше указанных действий

**Comment by belomaxorka** [comment]
Спасибо, будем разбираться.

**Comment by artems37rus** [comment]
\internal_data\cache\filecache\datastore
файл: tp_cat_forums.php
после добавления в админки не добавляет информацию о форуме, но после удаления успешно все пересоздает.
Скажите у вас также?

**Comment by belomaxorka** [comment]
Исправлено в этой версии: [тык](https://github.com/torrentpier/torrentpier/releases/tag/v2.4.0-alpha3) 😉
