### ISSUE TITLE
Логирование ошибок

### ISSUE THREAD

**Issue by Exile37** [torrentpier/torrentpier#77]
Логирование ошибок (любого типа) следует переделать в что-то более стандартное и опционально предупреждения хранить в базе данных, для быстрого и удобного доступа через админку, очистки и т.п.

https://packagist.org/packages/monolog/monolog - как вариант.
https://packagist.org/packages/psr/log - более "простое".

**Comment by VasyOk** [comment]
psr/log - это реализация [PSR-3](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-3-logger-interface.md). А monolog/monolog это мощная "обертка" на эту самую "реализацию".
monolog/monolog - это отличное предложение для логирования.

**Comment by KaRpIkS** [comment]
У меня складывается такое впечатление, что не новая версия трекера собирается, а Подготовка к палёту на марс....

**Comment by Exile37** [comment]
Качайте текущую версию из develop-ветки и ставьте, особых ошибок в ней уже как таковых нет. Никто не заставляет ждать полноценного завершения изменений в движке. А все они давно наболели, т.к. устарело все абсолютно и нужна система модификаций без изменений в файлах движка.

**Comment by Alexandersuz** [comment]
Движок стоит на месте и не обновляется, люди недовольны. В движок вносятся куча правок и обновлений, люди не довольны. Всё как всегда -_-

**Comment by KaRpIkS** [comment]
@Alexandersuz  Вы не так поняли что я хотел донести.

**Comment by Exile37** [comment]
Проясните для всех тогда, потому что метафоры с полетом в космос и среди разработчиков-то особо никто не понял.

**Comment by Exile37** [comment]
Реализовано.
