### ISSUE TITLE
Расширить второй параметр получения кеша

### ISSUE THREAD

**Issue by VasyOk** [torrentpier/torrentpier#95]
Если данных в кеше нет. выполняется второй параметр метода, который будет callback функцией.

``` php
$cache->get('namespace::key', function($cache, $key) {
    $data = [1,2,3,4,5];
    $cache->set($key, $data);
    return $data;
});
```

**Comment by Exileum** [comment]
It will be implemented in the long term with cache component replace. Closed for now.
